[package]
name = "whispercli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive", "cargo"] }
commandcrafter = "0.3.2"
[profile.dev]
opt-level = 1
[profile.release]
opt-level = 3

