[package]
name = "orion_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commandcrafter = "0.4.1"
inquire = "0.7.1"
