[package]
name = "orion_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
commandcrafter = "0.4.1"
git2 = "0.18.3"
inquire = "0.7.1"
walkdir = "2.5.0"
zip = "0.6.6"
